/*******************************************************************************
* Copyright (C) 2019-2024 Maxim Integrated Products, Inc., All rights Reserved.
*
* This software is protected by copyright laws of the United States and
* of foreign countries. This material may also be protected by patent laws
* and technology transfer regulations of the United States and of foreign
* countries. This software is furnished under a license agreement and/or a
* nondisclosure agreement and may only be used or reproduced in accordance
* with the terms of those agreements. Dissemination of this information to
* any party or parties not specified in the license agreement and/or
* nondisclosure agreement is expressly prohibited.
*
* The above copyright notice and this permission notice shall be included
* in all copies or substantial portions of the Software.
*
* THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
* OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
* MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
* IN NO EVENT SHALL MAXIM INTEGRATED BE LIABLE FOR ANY CLAIM, DAMAGES
* OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
* ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
* OTHER DEALINGS IN THE SOFTWARE.
*
* Except as contained in this notice, the name of Maxim Integrated
* Products, Inc. shall not be used except as stated in the Maxim Integrated
* Products, Inc. Branding Policy.
*
* The mere transfer of this software does not imply any licenses
* of trade secrets, proprietary technology, copyrights, patents,
* trademarks, maskwork rights, or any other form of intellectual
* property whatsoever. Maxim Integrated Products, Inc. retains all
* ownership rights.
*******************************************************************************/

// coughnet_kws_c20_c2d
// This file was @generated by ai8xize.py --test-dir synthed_net --prefix coughnet_kws_c20_c2d --checkpoint-file trained/qat_best_c2d.pth-q.tar --config-file networks/kws20-hwc.yaml --sample-input tests/sample_cough.npy --softmax --device MAX78000 --compact-data --mexpress --timer 0 --display-checkpoint --verbose --overwrite

// DO NOT EDIT - regenerate this file instead!

// Configuring 10 layers
// Input data: HWC
// Layer 0: 128x128, no pooling, conv1d with kernel size 1, stride 1, pad 0, ReLU, 100x128 output
// Layer 1: 100x128, no pooling, conv1d with kernel size 1, stride 1, pad 0, ReLU, 100x128 output
// Layer 2: 100x128, no pooling, conv1d with kernel size 1, stride 1, pad 0, ReLU, 50x128 output
// Layer 3: 50x128, no pooling, conv1d with kernel size 1, stride 1, pad 0, ReLU, 16x128 output
// Layer 4: 16x16x8, no pooling, conv2d with kernel size 3x3, stride 1/1, pad 1/1, ReLU, 32x16x8 output
// Layer 5: 32x16x8, no pooling, conv2d with kernel size 3x3, stride 1/1, pad 1/1, ReLU, 64x16x8 output
// Layer 6: 64x16x8, no pooling, conv2d with kernel size 3x3, stride 1/1, pad 1/1, ReLU, 64x16x8 output
// Layer 7: 64x16x8, no pooling, conv2d with kernel size 3x3, stride 1/1, pad 1/1, ReLU, 30x16x8 output
// Layer 8: 30x16x8, no pooling, conv2d with kernel size 3x3, stride 1/1, pad 1/1, ReLU, 7x16x8 output
// Layer 9: 7x16x8 flattened to 896x1x1, no pooling, linear, no activation, 20x1x1 output

// Final Scales: {0: 0, 1: 0, 2: 0, 3: 0, 4: 0, 5: 0, 6: 0, 7: 0, 8: 0, 9: 3}

#include <stdlib.h>
#include <stdint.h>
#include <string.h>
#include <stdio.h>
#include "mxc.h"
#include "gcfr_regs.h"
#include "cnn.h"
#include "weights.h"

void CNN_ISR(void)
{
  // Acknowledge interrupt to all quadrants
  *((volatile uint32_t *) 0x50100000) &= ~((1<<12) | 1);
  *((volatile uint32_t *) 0x50500000) &= ~((1<<12) | 1);
  *((volatile uint32_t *) 0x50900000) &= ~((1<<12) | 1);
  *((volatile uint32_t *) 0x50d00000) &= ~((1<<12) | 1);

  CNN_COMPLETE; // Signal that processing is complete
#ifdef CNN_INFERENCE_TIMER
  cnn_time = MXC_TMR_SW_Stop(CNN_INFERENCE_TIMER);
#else
  cnn_time = 1;
#endif
}

int cnn_continue(void)
{
  cnn_time = 0;

  *((volatile uint32_t *) 0x50100000) |= 1; // Re-enable quadrant 0

  return CNN_OK;
}

int cnn_stop(void)
{
  *((volatile uint32_t *) 0x50100000) &= ~1; // Disable quadrant 0

  return CNN_OK;
}

void memcpy32(uint32_t *dst, const uint32_t *src, int n)
{
  while (n-- > 0) {
    *dst++ = *src++;
  }
}

static const uint32_t kernels[] = KERNELS;

int cnn_load_weights(void)
{
  uint32_t len;
  volatile uint32_t *addr;
  const uint32_t *ptr = kernels;

  while ((addr = (volatile uint32_t *) *ptr++) != 0) {
    *((volatile uint8_t *) ((uint32_t) addr | 1)) = 0x01; // Set address
    len = *ptr++;
    while (len-- > 0)
      *addr++ = *ptr++;
  }

  return CNN_OK;
}

int cnn_load_bias(void)
{
  // Not used in this network
  return CNN_OK;
}

int cnn_init(void)
{
  *((volatile uint32_t *) 0x50001000) = 0x00000000; // AON control
  *((volatile uint32_t *) 0x50100000) = 0x00100008; // Stop SM
  *((volatile uint32_t *) 0x50100004) = 0x0000040e; // SRAM control
  *((volatile uint32_t *) 0x50100008) = 0x00000009; // Layer count
  *((volatile uint32_t *) 0x50500000) = 0x00100008; // Stop SM
  *((volatile uint32_t *) 0x50500004) = 0x0000040e; // SRAM control
  *((volatile uint32_t *) 0x50500008) = 0x00000009; // Layer count
  *((volatile uint32_t *) 0x50900000) = 0x00100008; // Stop SM
  *((volatile uint32_t *) 0x50900004) = 0x0000040e; // SRAM control
  *((volatile uint32_t *) 0x50900008) = 0x00000009; // Layer count
  *((volatile uint32_t *) 0x50d00000) = 0x00100008; // Stop SM
  *((volatile uint32_t *) 0x50d00004) = 0x0000040e; // SRAM control
  *((volatile uint32_t *) 0x50d00008) = 0x00000009; // Layer count

  return CNN_OK;
}

int cnn_configure(void)
{
  // Layer 0 quadrant 0
  *((volatile uint32_t *) 0x50100010) = 0x0000007f; // Rows
  *((volatile uint32_t *) 0x50100310) = 0x00000800; // SRAM write ptr
  *((volatile uint32_t *) 0x50100410) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50100490) = 0x00000001; // Write ptr multi-pass channel offs
  *((volatile uint32_t *) 0x50100590) = 0x0000eb20; // Layer control
  *((volatile uint32_t *) 0x50100a10) = 0x00019811; // Layer control 2
  *((volatile uint32_t *) 0x50100610) = 0x00000678; // Mask offset and count
  *((volatile uint32_t *) 0x50100110) = 0x00001100; // 1D
  *((volatile uint32_t *) 0x50100790) = 0x00022000; // Post processing register
  *((volatile uint32_t *) 0x50100710) = 0xffffffff; // Mask and processor enables

  // Layer 0 quadrant 1
  *((volatile uint32_t *) 0x50500010) = 0x0000007f; // Rows
  *((volatile uint32_t *) 0x50500310) = 0x00000800; // SRAM write ptr
  *((volatile uint32_t *) 0x50500410) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50500490) = 0x00000001; // Write ptr multi-pass channel offs
  *((volatile uint32_t *) 0x50500590) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50500a10) = 0x00019811; // Layer control 2
  *((volatile uint32_t *) 0x50500610) = 0x00000678; // Mask offset and count
  *((volatile uint32_t *) 0x50500110) = 0x00001100; // 1D
  *((volatile uint32_t *) 0x50500790) = 0x00022000; // Post processing register
  *((volatile uint32_t *) 0x50500710) = 0xffffffff; // Mask and processor enables

  // Layer 0 quadrant 2
  *((volatile uint32_t *) 0x50900010) = 0x0000007f; // Rows
  *((volatile uint32_t *) 0x50900310) = 0x00000800; // SRAM write ptr
  *((volatile uint32_t *) 0x50900410) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50900490) = 0x00000001; // Write ptr multi-pass channel offs
  *((volatile uint32_t *) 0x50900590) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50900a10) = 0x00019811; // Layer control 2
  *((volatile uint32_t *) 0x50900610) = 0x00000678; // Mask offset and count
  *((volatile uint32_t *) 0x50900110) = 0x00001100; // 1D
  *((volatile uint32_t *) 0x50900790) = 0x00022000; // Post processing register
  *((volatile uint32_t *) 0x50900710) = 0xffffffff; // Mask and processor enables

  // Layer 0 quadrant 3
  *((volatile uint32_t *) 0x50d00010) = 0x0000007f; // Rows
  *((volatile uint32_t *) 0x50d00310) = 0x00000800; // SRAM write ptr
  *((volatile uint32_t *) 0x50d00410) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50d00490) = 0x00000001; // Write ptr multi-pass channel offs
  *((volatile uint32_t *) 0x50d00590) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50d00a10) = 0x00019811; // Layer control 2
  *((volatile uint32_t *) 0x50d00610) = 0x00000678; // Mask offset and count
  *((volatile uint32_t *) 0x50d00110) = 0x00001100; // 1D
  *((volatile uint32_t *) 0x50d00790) = 0x00022000; // Post processing register
  *((volatile uint32_t *) 0x50d00710) = 0xffffffff; // Mask and processor enables

  // Layer 1 quadrant 0
  *((volatile uint32_t *) 0x50100014) = 0x0000007f; // Rows
  *((volatile uint32_t *) 0x50100414) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50100494) = 0x00000001; // Write ptr multi-pass channel offs
  *((volatile uint32_t *) 0x50100514) = 0x00000800; // SRAM read ptr
  *((volatile uint32_t *) 0x50100594) = 0x0000eb20; // Layer control
  *((volatile uint32_t *) 0x50100a14) = 0x00019811; // Layer control 2
  *((volatile uint32_t *) 0x50100614) = 0x21c02838; // Mask offset and count
  *((volatile uint32_t *) 0x50100114) = 0x00001100; // 1D
  *((volatile uint32_t *) 0x50100794) = 0x00002000; // Post processing register
  *((volatile uint32_t *) 0x50100714) = 0xffffffff; // Mask and processor enables

  // Layer 1 quadrant 1
  *((volatile uint32_t *) 0x50500014) = 0x0000007f; // Rows
  *((volatile uint32_t *) 0x50500414) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50500494) = 0x00000001; // Write ptr multi-pass channel offs
  *((volatile uint32_t *) 0x50500514) = 0x00000800; // SRAM read ptr
  *((volatile uint32_t *) 0x50500594) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50500a14) = 0x00019811; // Layer control 2
  *((volatile uint32_t *) 0x50500614) = 0x21c02838; // Mask offset and count
  *((volatile uint32_t *) 0x50500114) = 0x00001100; // 1D
  *((volatile uint32_t *) 0x50500794) = 0x00002000; // Post processing register
  *((volatile uint32_t *) 0x50500714) = 0xffffffff; // Mask and processor enables

  // Layer 1 quadrant 2
  *((volatile uint32_t *) 0x50900014) = 0x0000007f; // Rows
  *((volatile uint32_t *) 0x50900414) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50900494) = 0x00000001; // Write ptr multi-pass channel offs
  *((volatile uint32_t *) 0x50900514) = 0x00000800; // SRAM read ptr
  *((volatile uint32_t *) 0x50900594) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50900a14) = 0x00019811; // Layer control 2
  *((volatile uint32_t *) 0x50900614) = 0x21c02838; // Mask offset and count
  *((volatile uint32_t *) 0x50900114) = 0x00001100; // 1D
  *((volatile uint32_t *) 0x50900794) = 0x00002000; // Post processing register
  *((volatile uint32_t *) 0x50900714) = 0xffffffff; // Mask and processor enables

  // Layer 1 quadrant 3
  *((volatile uint32_t *) 0x50d00014) = 0x0000007f; // Rows
  *((volatile uint32_t *) 0x50d00414) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50d00494) = 0x00000001; // Write ptr multi-pass channel offs
  *((volatile uint32_t *) 0x50d00514) = 0x00000800; // SRAM read ptr
  *((volatile uint32_t *) 0x50d00594) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50d00a14) = 0x00019811; // Layer control 2
  *((volatile uint32_t *) 0x50d00614) = 0x21c02838; // Mask offset and count
  *((volatile uint32_t *) 0x50d00114) = 0x00001100; // 1D
  *((volatile uint32_t *) 0x50d00794) = 0x00002000; // Post processing register
  *((volatile uint32_t *) 0x50d00714) = 0x000f000f; // Mask and processor enables

  // Layer 2 quadrant 0
  *((volatile uint32_t *) 0x50100018) = 0x0000007f; // Rows
  *((volatile uint32_t *) 0x50100318) = 0x00000800; // SRAM write ptr
  *((volatile uint32_t *) 0x50100418) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50100598) = 0x0000eb20; // Layer control
  *((volatile uint32_t *) 0x50100a18) = 0x00018801; // Layer control 2
  *((volatile uint32_t *) 0x50100618) = 0x28802b98; // Mask offset and count
  *((volatile uint32_t *) 0x50100118) = 0x00001100; // 1D
  *((volatile uint32_t *) 0x50100798) = 0x00002000; // Post processing register
  *((volatile uint32_t *) 0x50100718) = 0xffffffff; // Mask and processor enables

  // Layer 2 quadrant 1
  *((volatile uint32_t *) 0x50500018) = 0x0000007f; // Rows
  *((volatile uint32_t *) 0x50500318) = 0x00000800; // SRAM write ptr
  *((volatile uint32_t *) 0x50500418) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50500598) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50500a18) = 0x00018801; // Layer control 2
  *((volatile uint32_t *) 0x50500618) = 0x28802b98; // Mask offset and count
  *((volatile uint32_t *) 0x50500118) = 0x00001100; // 1D
  *((volatile uint32_t *) 0x50500798) = 0x00002000; // Post processing register
  *((volatile uint32_t *) 0x50500718) = 0xffffffff; // Mask and processor enables

  // Layer 2 quadrant 2
  *((volatile uint32_t *) 0x50900018) = 0x0000007f; // Rows
  *((volatile uint32_t *) 0x50900318) = 0x00000800; // SRAM write ptr
  *((volatile uint32_t *) 0x50900418) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50900598) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50900a18) = 0x00018801; // Layer control 2
  *((volatile uint32_t *) 0x50900618) = 0x28802b98; // Mask offset and count
  *((volatile uint32_t *) 0x50900118) = 0x00001100; // 1D
  *((volatile uint32_t *) 0x50900798) = 0x00002000; // Post processing register
  *((volatile uint32_t *) 0x50900718) = 0xffffffff; // Mask and processor enables

  // Layer 2 quadrant 3
  *((volatile uint32_t *) 0x50d00018) = 0x0000007f; // Rows
  *((volatile uint32_t *) 0x50d00318) = 0x00000800; // SRAM write ptr
  *((volatile uint32_t *) 0x50d00418) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50d00598) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50d00a18) = 0x00018801; // Layer control 2
  *((volatile uint32_t *) 0x50d00618) = 0x28802b98; // Mask offset and count
  *((volatile uint32_t *) 0x50d00118) = 0x00001100; // 1D
  *((volatile uint32_t *) 0x50d00798) = 0x00002000; // Post processing register
  *((volatile uint32_t *) 0x50d00718) = 0x000f000f; // Mask and processor enables

  // Layer 3 quadrant 0
  *((volatile uint32_t *) 0x5010001c) = 0x0000007f; // Rows
  *((volatile uint32_t *) 0x5010041c) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x5010051c) = 0x00000800; // SRAM read ptr
  *((volatile uint32_t *) 0x5010059c) = 0x0000eb20; // Layer control
  *((volatile uint32_t *) 0x50100a1c) = 0x00007800; // Layer control 2
  *((volatile uint32_t *) 0x5010061c) = 0x18c01938; // Mask offset and count
  *((volatile uint32_t *) 0x5010011c) = 0x00001100; // 1D
  *((volatile uint32_t *) 0x5010079c) = 0x00002000; // Post processing register
  *((volatile uint32_t *) 0x5010071c) = 0xffffffff; // Mask and processor enables

  // Layer 3 quadrant 1
  *((volatile uint32_t *) 0x5050001c) = 0x0000007f; // Rows
  *((volatile uint32_t *) 0x5050041c) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x5050051c) = 0x00000800; // SRAM read ptr
  *((volatile uint32_t *) 0x5050059c) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50500a1c) = 0x00007800; // Layer control 2
  *((volatile uint32_t *) 0x5050061c) = 0x18c01938; // Mask offset and count
  *((volatile uint32_t *) 0x5050011c) = 0x00001100; // 1D
  *((volatile uint32_t *) 0x5050079c) = 0x00002000; // Post processing register
  *((volatile uint32_t *) 0x5050071c) = 0xffffffff; // Mask and processor enables

  // Layer 3 quadrant 2
  *((volatile uint32_t *) 0x5090001c) = 0x0000007f; // Rows
  *((volatile uint32_t *) 0x5090041c) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x5090051c) = 0x00000800; // SRAM read ptr
  *((volatile uint32_t *) 0x5090059c) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50900a1c) = 0x00007800; // Layer control 2
  *((volatile uint32_t *) 0x5090061c) = 0x18c01938; // Mask offset and count
  *((volatile uint32_t *) 0x5090011c) = 0x00001100; // 1D
  *((volatile uint32_t *) 0x5090079c) = 0x00002000; // Post processing register
  *((volatile uint32_t *) 0x5090071c) = 0xffffffff; // Mask and processor enables

  // Layer 3 quadrant 3
  *((volatile uint32_t *) 0x50d0001c) = 0x0000007f; // Rows
  *((volatile uint32_t *) 0x50d0041c) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50d0051c) = 0x00000800; // SRAM read ptr
  *((volatile uint32_t *) 0x50d0059c) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50d00a1c) = 0x00007800; // Layer control 2
  *((volatile uint32_t *) 0x50d0061c) = 0x18c01938; // Mask offset and count
  *((volatile uint32_t *) 0x50d0011c) = 0x00001100; // 1D
  *((volatile uint32_t *) 0x50d0079c) = 0x00002000; // Post processing register
  *((volatile uint32_t *) 0x50d0071c) = 0x00030003; // Mask and processor enables

  // Layer 4 quadrant 0
  *((volatile uint32_t *) 0x50100020) = 0x00010011; // Rows
  *((volatile uint32_t *) 0x501000a0) = 0x00010009; // Columns
  *((volatile uint32_t *) 0x50100320) = 0x00002800; // SRAM write ptr
  *((volatile uint32_t *) 0x50100420) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x501005a0) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50100a20) = 0x0000f800; // Layer control 2
  *((volatile uint32_t *) 0x50100620) = 0x04e005d8; // Mask offset and count
  *((volatile uint32_t *) 0x501006a0) = 0x00000007; // TRAM ptr max
  *((volatile uint32_t *) 0x50100720) = 0xffffffff; // Mask and processor enables

  // Layer 4 quadrant 1
  *((volatile uint32_t *) 0x50500020) = 0x00010011; // Rows
  *((volatile uint32_t *) 0x505000a0) = 0x00010009; // Columns
  *((volatile uint32_t *) 0x50500320) = 0x00002800; // SRAM write ptr
  *((volatile uint32_t *) 0x50500420) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x505005a0) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50500a20) = 0x0000f800; // Layer control 2
  *((volatile uint32_t *) 0x50500620) = 0x04e005d8; // Mask offset and count
  *((volatile uint32_t *) 0x505006a0) = 0x00000007; // TRAM ptr max

  // Layer 4 quadrant 2
  *((volatile uint32_t *) 0x50900020) = 0x00010011; // Rows
  *((volatile uint32_t *) 0x509000a0) = 0x00010009; // Columns
  *((volatile uint32_t *) 0x50900320) = 0x00002800; // SRAM write ptr
  *((volatile uint32_t *) 0x50900420) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x509005a0) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50900a20) = 0x0000f800; // Layer control 2
  *((volatile uint32_t *) 0x50900620) = 0x04e005d8; // Mask offset and count
  *((volatile uint32_t *) 0x509006a0) = 0x00000007; // TRAM ptr max

  // Layer 4 quadrant 3
  *((volatile uint32_t *) 0x50d00020) = 0x00010011; // Rows
  *((volatile uint32_t *) 0x50d000a0) = 0x00010009; // Columns
  *((volatile uint32_t *) 0x50d00320) = 0x00002800; // SRAM write ptr
  *((volatile uint32_t *) 0x50d00420) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50d005a0) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50d00a20) = 0x0000f800; // Layer control 2
  *((volatile uint32_t *) 0x50d00620) = 0x04e005d8; // Mask offset and count
  *((volatile uint32_t *) 0x50d006a0) = 0x00000007; // TRAM ptr max

  // Layer 5 quadrant 0
  *((volatile uint32_t *) 0x50100024) = 0x00010011; // Rows
  *((volatile uint32_t *) 0x501000a4) = 0x00010009; // Columns
  *((volatile uint32_t *) 0x50100424) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50100524) = 0x00000800; // SRAM read ptr
  *((volatile uint32_t *) 0x501005a4) = 0x00006b20; // Layer control
  *((volatile uint32_t *) 0x50100a24) = 0x0001f800; // Layer control 2
  *((volatile uint32_t *) 0x50100624) = 0x05e007d8; // Mask offset and count
  *((volatile uint32_t *) 0x501006a4) = 0x00000007; // TRAM ptr max
  *((volatile uint32_t *) 0x501007a4) = 0x00004000; // Post processing register
  *((volatile uint32_t *) 0x50100724) = 0xfff0fff0; // Mask and processor enables

  // Layer 5 quadrant 1
  *((volatile uint32_t *) 0x50500024) = 0x00010011; // Rows
  *((volatile uint32_t *) 0x505000a4) = 0x00010009; // Columns
  *((volatile uint32_t *) 0x50500424) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50500524) = 0x00000800; // SRAM read ptr
  *((volatile uint32_t *) 0x505005a4) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50500a24) = 0x0001f800; // Layer control 2
  *((volatile uint32_t *) 0x50500624) = 0x05e007d8; // Mask offset and count
  *((volatile uint32_t *) 0x505006a4) = 0x00000007; // TRAM ptr max
  *((volatile uint32_t *) 0x505007a4) = 0x00004000; // Post processing register
  *((volatile uint32_t *) 0x50500724) = 0xffffffff; // Mask and processor enables

  // Layer 5 quadrant 2
  *((volatile uint32_t *) 0x50900024) = 0x00010011; // Rows
  *((volatile uint32_t *) 0x509000a4) = 0x00010009; // Columns
  *((volatile uint32_t *) 0x50900424) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50900524) = 0x00000800; // SRAM read ptr
  *((volatile uint32_t *) 0x509005a4) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50900a24) = 0x0001f800; // Layer control 2
  *((volatile uint32_t *) 0x50900624) = 0x05e007d8; // Mask offset and count
  *((volatile uint32_t *) 0x509006a4) = 0x00000007; // TRAM ptr max
  *((volatile uint32_t *) 0x509007a4) = 0x00004000; // Post processing register
  *((volatile uint32_t *) 0x50900724) = 0x000f000f; // Mask and processor enables

  // Layer 5 quadrant 3
  *((volatile uint32_t *) 0x50d00024) = 0x00010011; // Rows
  *((volatile uint32_t *) 0x50d000a4) = 0x00010009; // Columns
  *((volatile uint32_t *) 0x50d00424) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50d00524) = 0x00000800; // SRAM read ptr
  *((volatile uint32_t *) 0x50d005a4) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50d00a24) = 0x0001f800; // Layer control 2
  *((volatile uint32_t *) 0x50d00624) = 0x05e007d8; // Mask offset and count
  *((volatile uint32_t *) 0x50d006a4) = 0x00000007; // TRAM ptr max
  *((volatile uint32_t *) 0x50d007a4) = 0x00004000; // Post processing register

  // Layer 6 quadrant 0
  *((volatile uint32_t *) 0x50100028) = 0x00010011; // Rows
  *((volatile uint32_t *) 0x501000a8) = 0x00010009; // Columns
  *((volatile uint32_t *) 0x50100328) = 0x00000800; // SRAM write ptr
  *((volatile uint32_t *) 0x50100428) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x501005a8) = 0x0000eb20; // Layer control
  *((volatile uint32_t *) 0x50100a28) = 0x0001f800; // Layer control 2
  *((volatile uint32_t *) 0x50100628) = 0x00c002b8; // Mask offset and count
  *((volatile uint32_t *) 0x501006a8) = 0x00000007; // TRAM ptr max
  *((volatile uint32_t *) 0x501007a8) = 0x00002000; // Post processing register
  *((volatile uint32_t *) 0x50100728) = 0xffffffff; // Mask and processor enables

  // Layer 6 quadrant 1
  *((volatile uint32_t *) 0x50500028) = 0x00010011; // Rows
  *((volatile uint32_t *) 0x505000a8) = 0x00010009; // Columns
  *((volatile uint32_t *) 0x50500328) = 0x00000800; // SRAM write ptr
  *((volatile uint32_t *) 0x50500428) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x505005a8) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50500a28) = 0x0001f800; // Layer control 2
  *((volatile uint32_t *) 0x50500628) = 0x00c002b8; // Mask offset and count
  *((volatile uint32_t *) 0x505006a8) = 0x00000007; // TRAM ptr max
  *((volatile uint32_t *) 0x505007a8) = 0x00002000; // Post processing register
  *((volatile uint32_t *) 0x50500728) = 0xffffffff; // Mask and processor enables

  // Layer 6 quadrant 2
  *((volatile uint32_t *) 0x50900028) = 0x00010011; // Rows
  *((volatile uint32_t *) 0x509000a8) = 0x00010009; // Columns
  *((volatile uint32_t *) 0x50900328) = 0x00000800; // SRAM write ptr
  *((volatile uint32_t *) 0x50900428) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x509005a8) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50900a28) = 0x0001f800; // Layer control 2
  *((volatile uint32_t *) 0x50900628) = 0x00c002b8; // Mask offset and count
  *((volatile uint32_t *) 0x509006a8) = 0x00000007; // TRAM ptr max
  *((volatile uint32_t *) 0x509007a8) = 0x00002000; // Post processing register
  *((volatile uint32_t *) 0x50900728) = 0xffffffff; // Mask and processor enables

  // Layer 6 quadrant 3
  *((volatile uint32_t *) 0x50d00028) = 0x00010011; // Rows
  *((volatile uint32_t *) 0x50d000a8) = 0x00010009; // Columns
  *((volatile uint32_t *) 0x50d00328) = 0x00000800; // SRAM write ptr
  *((volatile uint32_t *) 0x50d00428) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50d005a8) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50d00a28) = 0x0001f800; // Layer control 2
  *((volatile uint32_t *) 0x50d00628) = 0x00c002b8; // Mask offset and count
  *((volatile uint32_t *) 0x50d006a8) = 0x00000007; // TRAM ptr max
  *((volatile uint32_t *) 0x50d007a8) = 0x00002000; // Post processing register
  *((volatile uint32_t *) 0x50d00728) = 0xffffffff; // Mask and processor enables

  // Layer 7 quadrant 0
  *((volatile uint32_t *) 0x5010002c) = 0x00010011; // Rows
  *((volatile uint32_t *) 0x501000ac) = 0x00010009; // Columns
  *((volatile uint32_t *) 0x5010032c) = 0x00010000; // SRAM write ptr
  *((volatile uint32_t *) 0x5010042c) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x5010052c) = 0x00000800; // SRAM read ptr
  *((volatile uint32_t *) 0x501005ac) = 0x0000eb20; // Layer control
  *((volatile uint32_t *) 0x50100a2c) = 0x0000f800; // Layer control 2
  *((volatile uint32_t *) 0x5010062c) = 0x02c003b8; // Mask offset and count
  *((volatile uint32_t *) 0x501006ac) = 0x00000007; // TRAM ptr max
  *((volatile uint32_t *) 0x5010072c) = 0xffffffff; // Mask and processor enables

  // Layer 7 quadrant 1
  *((volatile uint32_t *) 0x5050002c) = 0x00010011; // Rows
  *((volatile uint32_t *) 0x505000ac) = 0x00010009; // Columns
  *((volatile uint32_t *) 0x5050032c) = 0x00010000; // SRAM write ptr
  *((volatile uint32_t *) 0x5050042c) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x5050052c) = 0x00000800; // SRAM read ptr
  *((volatile uint32_t *) 0x505005ac) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50500a2c) = 0x0000f800; // Layer control 2
  *((volatile uint32_t *) 0x5050062c) = 0x02c003b8; // Mask offset and count
  *((volatile uint32_t *) 0x505006ac) = 0x00000007; // TRAM ptr max
  *((volatile uint32_t *) 0x5050072c) = 0xffffffff; // Mask and processor enables

  // Layer 7 quadrant 2
  *((volatile uint32_t *) 0x5090002c) = 0x00010011; // Rows
  *((volatile uint32_t *) 0x509000ac) = 0x00010009; // Columns
  *((volatile uint32_t *) 0x5090032c) = 0x00010000; // SRAM write ptr
  *((volatile uint32_t *) 0x5090042c) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x5090052c) = 0x00000800; // SRAM read ptr
  *((volatile uint32_t *) 0x509005ac) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50900a2c) = 0x0000f800; // Layer control 2
  *((volatile uint32_t *) 0x5090062c) = 0x02c003b8; // Mask offset and count
  *((volatile uint32_t *) 0x509006ac) = 0x00000007; // TRAM ptr max
  *((volatile uint32_t *) 0x5090072c) = 0xffffffff; // Mask and processor enables

  // Layer 7 quadrant 3
  *((volatile uint32_t *) 0x50d0002c) = 0x00010011; // Rows
  *((volatile uint32_t *) 0x50d000ac) = 0x00010009; // Columns
  *((volatile uint32_t *) 0x50d0032c) = 0x00010000; // SRAM write ptr
  *((volatile uint32_t *) 0x50d0042c) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50d0052c) = 0x00000800; // SRAM read ptr
  *((volatile uint32_t *) 0x50d005ac) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50d00a2c) = 0x0000f800; // Layer control 2
  *((volatile uint32_t *) 0x50d0062c) = 0x02c003b8; // Mask offset and count
  *((volatile uint32_t *) 0x50d006ac) = 0x00000007; // TRAM ptr max
  *((volatile uint32_t *) 0x50d0072c) = 0xffffffff; // Mask and processor enables

  // Layer 8 quadrant 0
  *((volatile uint32_t *) 0x50100030) = 0x00010011; // Rows
  *((volatile uint32_t *) 0x501000b0) = 0x00010009; // Columns
  *((volatile uint32_t *) 0x50100430) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x501005b0) = 0x0000cb20; // Layer control
  *((volatile uint32_t *) 0x50100a30) = 0x00003000; // Layer control 2
  *((volatile uint32_t *) 0x50100630) = 0x04e00510; // Mask offset and count
  *((volatile uint32_t *) 0x501006b0) = 0x00000007; // TRAM ptr max
  *((volatile uint32_t *) 0x501007b0) = 0x00022000; // Post processing register

  // Layer 8 quadrant 1
  *((volatile uint32_t *) 0x50500030) = 0x00010011; // Rows
  *((volatile uint32_t *) 0x505000b0) = 0x00010009; // Columns
  *((volatile uint32_t *) 0x50500430) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x505005b0) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50500a30) = 0x00003000; // Layer control 2
  *((volatile uint32_t *) 0x50500630) = 0x04e00510; // Mask offset and count
  *((volatile uint32_t *) 0x505006b0) = 0x00000007; // TRAM ptr max
  *((volatile uint32_t *) 0x505007b0) = 0x00022000; // Post processing register

  // Layer 8 quadrant 2
  *((volatile uint32_t *) 0x50900030) = 0x00010011; // Rows
  *((volatile uint32_t *) 0x509000b0) = 0x00010009; // Columns
  *((volatile uint32_t *) 0x50900430) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x509005b0) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50900a30) = 0x00003000; // Layer control 2
  *((volatile uint32_t *) 0x50900630) = 0x04e00510; // Mask offset and count
  *((volatile uint32_t *) 0x509006b0) = 0x00000007; // TRAM ptr max
  *((volatile uint32_t *) 0x509007b0) = 0x00022000; // Post processing register
  *((volatile uint32_t *) 0x50900730) = 0xfffcfffc; // Mask and processor enables

  // Layer 8 quadrant 3
  *((volatile uint32_t *) 0x50d00030) = 0x00010011; // Rows
  *((volatile uint32_t *) 0x50d000b0) = 0x00010009; // Columns
  *((volatile uint32_t *) 0x50d00430) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50d005b0) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50d00a30) = 0x00003000; // Layer control 2
  *((volatile uint32_t *) 0x50d00630) = 0x04e00510; // Mask offset and count
  *((volatile uint32_t *) 0x50d006b0) = 0x00000007; // TRAM ptr max
  *((volatile uint32_t *) 0x50d007b0) = 0x00022000; // Post processing register
  *((volatile uint32_t *) 0x50d00730) = 0xffffffff; // Mask and processor enables

  // Layer 9 quadrant 0
  *((volatile uint32_t *) 0x50100334) = 0x00000800; // SRAM write ptr
  *((volatile uint32_t *) 0x501003b4) = 0x00000001; // Write ptr time slot offs
  *((volatile uint32_t *) 0x50100434) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x501005b4) = 0x00010920; // Layer control
  *((volatile uint32_t *) 0x50100a34) = 0x0000980f; // Layer control 2
  *((volatile uint32_t *) 0x50100634) = 0x46e096d8; // Mask offset and count
  *((volatile uint32_t *) 0x50100134) = 0x00000100; // 1D
  *((volatile uint32_t *) 0x501006b4) = 0x007f00ff; // TRAM ptr max
  *((volatile uint32_t *) 0x501007b4) = 0x081e4000; // Post processing register
  *((volatile uint32_t *) 0x50100734) = 0x007f007f; // Mask and processor enables

  // Layer 9 quadrant 1
  *((volatile uint32_t *) 0x50500334) = 0x00000800; // SRAM write ptr
  *((volatile uint32_t *) 0x505003b4) = 0x00000001; // Write ptr time slot offs
  *((volatile uint32_t *) 0x50500434) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x505005b4) = 0x00010920; // Layer control
  *((volatile uint32_t *) 0x50500a34) = 0x0000980f; // Layer control 2
  *((volatile uint32_t *) 0x50500634) = 0x46e096d8; // Mask offset and count
  *((volatile uint32_t *) 0x50500134) = 0x00000100; // 1D
  *((volatile uint32_t *) 0x505006b4) = 0x007f00ff; // TRAM ptr max
  *((volatile uint32_t *) 0x505007b4) = 0x081e4000; // Post processing register

  // Layer 9 quadrant 2
  *((volatile uint32_t *) 0x50900334) = 0x00000800; // SRAM write ptr
  *((volatile uint32_t *) 0x509003b4) = 0x00000001; // Write ptr time slot offs
  *((volatile uint32_t *) 0x50900434) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x509005b4) = 0x00010920; // Layer control
  *((volatile uint32_t *) 0x50900a34) = 0x0000980f; // Layer control 2
  *((volatile uint32_t *) 0x50900634) = 0x46e096d8; // Mask offset and count
  *((volatile uint32_t *) 0x50900134) = 0x00000100; // 1D
  *((volatile uint32_t *) 0x509006b4) = 0x007f00ff; // TRAM ptr max
  *((volatile uint32_t *) 0x509007b4) = 0x081e4000; // Post processing register

  // Layer 9 quadrant 3
  *((volatile uint32_t *) 0x50d00334) = 0x00000800; // SRAM write ptr
  *((volatile uint32_t *) 0x50d003b4) = 0x00000001; // Write ptr time slot offs
  *((volatile uint32_t *) 0x50d00434) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50d005b4) = 0x00010920; // Layer control
  *((volatile uint32_t *) 0x50d00a34) = 0x0000980f; // Layer control 2
  *((volatile uint32_t *) 0x50d00634) = 0x46e096d8; // Mask offset and count
  *((volatile uint32_t *) 0x50d00134) = 0x00000100; // 1D
  *((volatile uint32_t *) 0x50d006b4) = 0x007f00ff; // TRAM ptr max
  *((volatile uint32_t *) 0x50d007b4) = 0x081e4000; // Post processing register


  return CNN_OK;
}

int cnn_start(void)
{
  cnn_time = 0;

  *((volatile uint32_t *) 0x50100000) = 0x00100808; // Enable quadrant 0
  *((volatile uint32_t *) 0x50500000) = 0x00100809; // Enable quadrant 1
  *((volatile uint32_t *) 0x50900000) = 0x00100809; // Enable quadrant 2
  *((volatile uint32_t *) 0x50d00000) = 0x00100809; // Enable quadrant 3

#ifdef CNN_INFERENCE_TIMER
  MXC_TMR_SW_Start(CNN_INFERENCE_TIMER);
#endif

  CNN_START; // Allow capture of processing time
  *((volatile uint32_t *) 0x50100000) = 0x00100009; // Master enable quadrant 0

  return CNN_OK;
}

int cnn_unload(uint32_t *out_buf)
{
  volatile uint32_t *addr;

  // Custom unload for this network, layer 9: 32-bit data, shape: (20, 1, 1)
  addr = (volatile uint32_t *) 0x50402000;
  *out_buf++ = (*addr++) << 3;
  *out_buf++ = (*addr++) << 3;
  *out_buf++ = (*addr++) << 3;
  *out_buf++ = (*addr++) << 3;
  addr = (volatile uint32_t *) 0x5040a000;
  *out_buf++ = (*addr++) << 3;
  *out_buf++ = (*addr++) << 3;
  *out_buf++ = (*addr++) << 3;
  *out_buf++ = (*addr++) << 3;
  addr = (volatile uint32_t *) 0x50412000;
  *out_buf++ = (*addr++) << 3;
  *out_buf++ = (*addr++) << 3;
  *out_buf++ = (*addr++) << 3;
  *out_buf++ = (*addr++) << 3;
  addr = (volatile uint32_t *) 0x5041a000;
  *out_buf++ = (*addr++) << 3;
  *out_buf++ = (*addr++) << 3;
  *out_buf++ = (*addr++) << 3;
  *out_buf++ = (*addr++) << 3;
  addr = (volatile uint32_t *) 0x50802000;
  *out_buf++ = (*addr++) << 3;
  *out_buf++ = (*addr++) << 3;
  *out_buf++ = (*addr++) << 3;
  *out_buf++ = (*addr++) << 3;

  return CNN_OK;
}

int cnn_enable(uint32_t clock_source, uint32_t clock_divider)
{
  // Reset all domains, restore power to CNN
  MXC_GCFR->reg3 = 0xf; // Reset
  MXC_GCFR->reg1 = 0xf; // Mask memory
  MXC_GCFR->reg0 = 0xf; // Power
  MXC_GCFR->reg2 = 0x0; // Iso
  MXC_GCFR->reg3 = 0x0; // Reset

  MXC_GCR->pclkdiv = (MXC_GCR->pclkdiv & ~(MXC_F_GCR_PCLKDIV_CNNCLKDIV | MXC_F_GCR_PCLKDIV_CNNCLKSEL))
                     | clock_divider | clock_source;
  MXC_SYS_ClockEnable(MXC_SYS_PERIPH_CLOCK_CNN); // Enable CNN clock

  MXC_NVIC_SetVector(CNN_IRQn, CNN_ISR); // Set CNN complete vector

  return CNN_OK;
}

int cnn_boost_enable(mxc_gpio_regs_t *port, uint32_t pin)
{
  mxc_gpio_cfg_t gpio_out;
  gpio_out.port = port;
  gpio_out.mask = pin;
  gpio_out.pad = MXC_GPIO_PAD_NONE;
  gpio_out.func = MXC_GPIO_FUNC_OUT;
  MXC_GPIO_Config(&gpio_out);
  MXC_GPIO_OutSet(gpio_out.port, gpio_out.mask);

  return CNN_OK;
}

int cnn_boost_disable(mxc_gpio_regs_t *port, uint32_t pin)
{
  mxc_gpio_cfg_t gpio_out;
  gpio_out.port = port;
  gpio_out.mask = pin;
  gpio_out.pad = MXC_GPIO_PAD_NONE;
  gpio_out.func = MXC_GPIO_FUNC_OUT;
  MXC_GPIO_Config(&gpio_out);
  MXC_GPIO_OutClr(gpio_out.port, gpio_out.mask);

  return CNN_OK;
}

int cnn_disable(void)
{
  // Disable CNN clock
  MXC_SYS_ClockDisable(MXC_SYS_PERIPH_CLOCK_CNN);

  // Disable power to CNN
  MXC_GCFR->reg3 = 0xf; // Reset
  MXC_GCFR->reg2 |= 0xf; // Iso
  MXC_GCFR->reg0 = 0x0; // Power
  MXC_GCFR->reg1 = 0x0; // Mask memory
  MXC_GCFR->reg3 = 0x0; // Reset

  return CNN_OK;
}

